spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL}

  ai:
    retry:
      max-attempts: 1
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      base-url: ${SPRING_AI_OPENAI_BASE_URL}
      chat:
        options:
          model: ${SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL}
          temperature: 0.3

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: ${APP_JWT_EXPIRATION}

google:
  factcheck:
    api:
      key: ${GOOGLE_FACTCHECK_API_KEY}
      url: https://factchecktools.googleapis.com/v1alpha1/claims:search